### ISSUE TITLE
HockeyApp upload successful but can't find build anywhere

### ISSUE THREAD

**Issue by jtaby** [nomad/shenzhen#162]
Hey, I just got hockeyapp distribution working. Here's my command and my output:

✗ ipa distribute:hockeyapp --token MY_TOKEN -i MY_IDENTIFIER -r beta
Build successfully uploaded to HockeyApp

However, I can't find the new build anywhere on the system. I bumped my version number and...nadda. Is there anywhere specifically I should be looking in? Any debugging I can do on my end?

**Comment by mattt** [comment]
As of #179, Shenzhen is uploading to `upload.hockeyapp.net` instead of `rink.hockeyapp.net`, as recommended by their support documents.

If you are still having trouble determining where uploaded builds are located on their system, I would recommend talking to HockeyApp support. If Shenzhen is posting to the latest API endpoint and the API is not behaving as documented or as self-reported, there's unfortunately very little to be done from the client side.
