### ISSUE TITLE
Store ipa build parameters in config file

### ISSUE THREAD

**Issue by KrauseFx** [nomad/shenzhen#200]
I'm a big fan of storing information needed to build on the file system to have it in version control. 
`xctool` does a pretty good job with the [xctool-args](https://github.com/facebook/xctool#configuration-xctool-args) file.

@mattt, if you agree, I'd prepare a pull request, to store the parameters of `shenzhen`, like the workspace to use, scheme, configuration and provisioning profile. 

Once stored, the developer only has to run `ipa build` to build the app.

What do you think?

**Comment by irons** [comment]
This is on our to-do list as well. I'm currently kicking the tires on shenzhen to find out if we want to adopt it as a build tool, or just use it in a deployment capacity, but putting all the configuration in the repository is highly desirable.

**Comment by toolbear** [comment]
As an alternative, you could:

a) wrap shenzhen in your own custom script or gem in a standard location for your projects
b) see if @mattt was amendable to incorporating [bkeepers/dotenv](https://github.com/bkeepers/dotenv) and manage all the things via environment variables
c) see if @matt was amenable to exposing more overrides via environment variables (maybe it already does for your use case and it isn't documented?)

Personally, I'm super happy with the approach all of `nomad-cli` takes WRT configuring itself with environment variables. Many of these things settings should be treated as secrets, or very by environment or developer. Environment variables are the perfect solution to this and are very automation and CI friendly.

**Comment by KrauseFx** [comment]
@toolbear I'm talking about the information **how to build the project** which is not secret and should be stored in version control.

Take a look how Facebook does it with [xctool-args](https://github.com/facebook/xctool#configuration-xctool-args). 

**Why?**

Many developers work on multiple projects, switching quite often. Being able to just enter `ipa build && ...` is really convenient and natural. 

I implemented something quite similar into [fastlane](https://github.com/KrauseFx/fastlane). Whenever I want to take new screenshots I only enter `snapshot`, when I want to release an update to the App Store I run `deliver`.

Storing the parameters required to build your app in the app's git repository itself is something we should aim for.

**Comment by toolbear** [comment]
I understand your motivation. My concern wasn't keeping secrets out of VCS. I'm just not convinced that anything more complicated than environment vars or wrapper scripts is warranted. I have the age-old unix bias of wanting my tools do one thing and do it well.

I'm not @matt nor am I a maintainer so carry on. I'll elaborate on my thinking for posterity.

---

You can't get much more universal and supported than plain old environment variables. If they get the job done, why complicate it further?

As it turns out [bkeepers/dotenv](https://github.com/bkeepers/dotenv) is already supported by `shenzhen`: [bin/ipa#L4](https://github.com/nomad/shenzhen/blob/master/bin/ipa#L4). Commit either `.env` or `.env.default` to your repo and I think you will have what you're asking for. 

Last thing I'll say about environment vars is that Xcode build configs use them and they play nicely with CI systems like Jenkins and Travis.

---

I'm sure you understood what I meant when I suggested wrapper scripts. I'll illustrate it anyway.

```console
bin
├── build
└── distribute
```
```sh
#!/usr/bin/env sh
# bin/distribute
set -euo pipefail
IFS=$'\n\t'

key=AKIAIOSFODNN7EXAMPLE
secret=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

ipa distribute:s3 -a ${key} -s ${secret} -b dev.us.my-cool-app
```
```console
$ cd my-awesome-app
$ build
…
$ distribute
…
```

There's nothing here that can't be done via `.env`; I'd use that instead of wrappers.

**Comment by mattt** [comment]
I agree completely with @toolbear—environment variables are the preferred method of specifying configuration. For what Shenzhen does, configuration files would only introduce another level of complexity.

If there's anything else to be done as far as incorporating `ENV` into Shenzhen, I'd happily review a PR.

**Comment by skywinder** [comment]
@mattt integration with https://github.com/bkeepers/dotenv is great feature! It would be nice to mention about `.env` file in readme!
