### ISSUE TITLE
"BUILD FAILED" and "ARCHIVE FAILED"

### ISSUE THREAD

**Issue by shannonchou** [nomad/shenzhen#204]
I renamed my project name, target name, scheme name recently. Then build failed frequently(not all the times). It prompt "\*\* ARCHIVE FAILED \*\*" or "\*\* BUILD FAILED \*\*". I can't find any error in --verbose mode.
But it is ok to build it in Xcode or using xcodebuild.
It looks like this:

```
ipa  build -w JiecaoNews.xcworkspace -s JiecaoNews -c Debug -d builds --clean --verbose > log.txt                                                     
2015-02-08 23:05:57.795 xcodebuild[14942:2853115]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/shannon/Library/Developer/Xcode/DeveloperPortal%206.1.1.db).
** BUILD FAILED **

** ARCHIVE FAILED **
```
I uploaded the verbose log here: 
[my log](http://yunpan.cn/cKUKdCLvYBqZy) （password：d910）

**Comment by mattt** [comment]
Shenzhen builds through an underlying `xcodebuild` call exclusively. If `ipa build` or `ipa archive` is failing  for any reason, it's because the command line options being passed are incorrect. It's unclear that there is anything to be changed in Shenzhen itself.

For help with your particular build settings, I would recommend Stack Overflow. Perhaps [this question](http://stackoverflow.com/questions/27534218/ios-command-line-build-fails-jenkins-xcode-6-1-storyboards) is related?

**Comment by mkodoitops** [comment]
@shannonchou I had the same issue today. My issue was caused by a build phase script which couldn't be found. Using xcode GUI it would work but not via command line. Sometimes report navigator can be much more useful.

**Comment by trisb** [comment]
@shannonchou I had the same issue today. My issue was caused by a build phase script which couldn't be found. Using xcode GUI it would work but not via command line. Sometimes report navigator can be much more useful.

**Comment by kenji21** [comment]
Thank you for the "clue", got same issue with a scripts phase calling a script which was not executable
