### ISSUE TITLE
iTunesConnect uploads fail if password has $ character, may result in account lockout

### ISSUE THREAD

**Issue by emaloney** [nomad/shenzhen#213]
If the iTunesConnect password contains a `$` character, attempts to `ipa distribute:itunesconnect` will fail.

The underlying error is revealed when running in `--verbose` mode:

```
Your Apple ID or password was entered incorrectly. (-20101)
```

Further, three failed authentication attempts will result in:

```
This Apple ID has been locked for security reasons. Visit iForgot to reset your account (https://iforgot.apple.com). (-20209)
```

**Comment by mattt** [comment]
I cannot reproduce. Any problematic characters that may occur in a password [are escaped with Shellwords](https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/plugins/itunesconnect.rb#L48). I can't account for how characters that would need to be escaped when passing as a flag to `$ ipa distribute:itunesconnect`, so that might be something to look into.

**Comment by mattt** [comment]
Possible duplicate of #189.
