### ISSUE TITLE
Sending build to HockeyApp always use the release type store

### ISSUE THREAD

**Issue by micky2be** [nomad/shenzhen#237]
Trying to upload my build using `ipa distribute:hockeyapp -r alpha` but HockeyApp keep telling me the download is disable for store app.

![screen shot 2015-03-27 at 13 13 43](https://cloud.githubusercontent.com/assets/728644/6862000/21892bdc-d483-11e4-9b2a-e658683b42c0.png)

**Comment by Mazyod** [comment]
I usually change the release type on the hockeyapp website itself, under the "Manage app" -> "Release type". Maybe shenzhen is just not able to switch it if it's already set?

**Comment by jhersh** [comment]
Quoth Hockey's site:

> Apps with the release type "store" cannot be distributed through HockeyApp.

The release type is set once, when you first create the app on hockey's website. You probably want to have at least one additional app on hockey, for alpha or beta builds, which can then be downloaded by your test users. You are probably uploading to the store app instead of your alpha app; make sure you are using the correct app identifier in your `ipa` command.

**Comment by mattt** [comment]
Thanks, @jhersh.
