### ISSUE TITLE
ipa info fails when .app file contains spaces

### ISSUE THREAD

**Issue by NachoSoto** [nomad/shenzhen#271]
``` bash
$ ipa info file.ipa
security: unable to open "/var/folders/yt/njd3fm3x4jd54hgtnck226l00000gn/T/d20150520-3119-gmtt8y/Payload/Khan" for reading: No such file or directory
undefined method `each' for nil:NilClass
```

The correct name of the .app file is `Khan Academy.app`, which lead me to believe that spaces on the filename is the problem. I imagine the bug is on [this line](https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/commands/info.rb#L19), buy my Ruby foo is not strong enough to see the actual problem.

Please let me know if I can provide more information. Thank you!

**Comment by truth3** [comment]
Hey NachoSoto, I think you need to use the following in your file name as it has a space ( I ran into similar problem with a few of my apps)

Khan\ Academy.ipa

Hope that helps!

**Comment by NachoSoto** [comment]
```bash
[NachoSoto(ci)]$ ipa info Khan\ Academy.ipa
security: unable to open "/var/folders/64/mk0rvr6974g22fxqprmpcl080000gn/T/d20150522-4846-85306z/Payload/Khan" for reading: No such file or directory
undefined method `each' for nil:NilClass
```

**Comment by truth3** [comment]
Hey Nacho, I think it may also have to deal with where your file is located and the permission on the folders because you get the security line. You can either move the IPA to a folder you know your user has permission to, or use the security command line tools to unlock the system keychain. This is an example of one of my applications that contains a space

ajrssd:Builds AJRSSD$ ipa info iForm\ ES.ipa
+-----------------------------+-----------------------------------------------------------------------+
| AppIDName                   | iForm ES       

You will notice if I try and run it without the forward slash, I will get the same error about file name not found, but no security warning because my user has permission to this folder.

ajrssd:Builds AJRSSD$ ipa info iForm ES.ipa
Missing or unspecified .ipa file

Hope that helps

**Comment by NachoSoto** [comment]
Thanks for the message @truth3.

The problem is something else, however.
If you notice, in my original message I explained that the issue is the `.app` file having a space, not the `.ipa`. Your example works because the application (`.app`) inside of the `ipa` does not have a space.

> You will notice if I try and run it without the forward slash, I will get the same error about file name not found

What you're getting is actually a **different** error, due to the fact that that command is passing 2 parameters: `iForm` and `ES.ipa`, and so the `.ipa` can't be found.

> but no security warning because my user has permission to this folder.

This problem has nothing to do with permissions. The security warning you're referring to is because the file cannot be found:

```
security: unable to open "/var/folders/64/mk0rvr6974g22fxqprmpcl080000gn/T/d20150522-4861-cu96c0/Payload/Khan" for reading: No such file or directory
```

Like I explained in my original message, the `.app` file inside of my `.ipa` contains a space: `Khan Academy.app`, but somehow [this line](https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/commands/info.rb#L19) is not handling that correctly.

**Comment by skywinder** [comment]
+1 Got same error as @NachoSoto (https://github.com/nomad/shenzhen/issues/271#issuecomment-104645601)

**Comment by skywinder** [comment]
Still fail.. So, I have to rename my project to work with your awesome tool.

**Comment by aenglund** [comment]
My pull request #273 solves this issue, doesn't it @skywinder? Would really like to see that one merged in soon...

**Comment by skywinder** [comment]
@aenglund Look like it really fix this this problem. @mattt please, check #273 .

**Comment by skywinder** [comment]
Kindly reminder.

**Comment by NachoSoto** [comment]
AFAIK this project is abandoned, but the author has not made that clear in the README.
