### ISSUE TITLE
ipa build Fail

### ISSUE THREAD

**Issue by zxm9988** [nomad/shenzhen#53]
I was created a empty project.  
I set Run/Archive  Build Configuration is Debug and set Use Debug for command-line builds

```
ipa build  
```

error 

```
 Configuration was not passed, defaulting to  Debug
 Building "nomad.xcodeproj" with Scheme "nomad" and Configuration "Debug"

     xcodebuild  nomad.xcodeproj
** BUILD FAILED **

The following build commands failed:
Check dependencies
(1 failure)
```

**Comment by phynet** [comment]
This an old **really old** post. But, I'm seeing this error now. 

I'm using 

    ipa  build --embed "iOS Team Provisioning Profile" --verbose

And is showing me this error:
    
    [BEROR]CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

Ok, so, if I sign it manually in (Build Settings --> Code Signing) with correct Provisioning  Profile AND Code Signing Identity, creates the ipa without problems. Although, this is not what I would like to do, because I need to automatize this step...

**What command should I use?** :weary:

Thank you very much for this lib.

Greetings

**Comment by KrauseFx** [comment]
In general, the ``--embed``` option will not be taken into account by `xcodebuild`, don't know if that's a bug or by design.

Your project must be correctly configured to use the correct provisioning profile.

**Comment by phynet** [comment]
So @KrauseFx , is mandatory to assign the Code signing and the Provisioning Profile in XCode IDE...

Running the xcrun command shows the same result, and is .... sad... 

    xcrun -sdk iphoneos PackageApplication -v ~/XcodeCommandLine/sym.root/Debug-iphonesimulator/MyTarget.app -o some_path

Thanks for the answer.

**Comment by KrauseFx** [comment]
Yes. That means your project settings are somehow incorrect.

**Comment by jonnyijapan** [comment]
Seeing this too, or something related. I do `ipa build` and it says "Configuration was not passed, defaulting to Debug", but there seems to be no way of specifying configuration to ipa, I look through help.

**Comment by phynet** [comment]
Well, I just wanted to say, even if this right now an old post... that I wrote this script to simplify signing when using automated testing (Because I needed to create an ipa and deploy it, without using Xcode while using Jenkins).  https://github.com/phynet/SSCodesigningXcode 

Thanks for your help @KrauseFx

**Comment by KrauseFx** [comment]
So what `SSCodesigningXcode` does: it modified the Xcode project code signing settings to match the correct ones, right? You'd run this **before** building using `shenzhen`.

If so, I implemented something similar integrated into `fastlane`: [update_project_code_signing](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/update_project_code_signing.rb)

**Comment by phynet** [comment]
Haha, yep, the same thing, didn't know you have this!!. But I'm newbie using Ruby so...I learned a little doing it anyway. :3 

I will take a look at your code. Thanks :+1:

**Comment by KrauseFx** [comment]
Cool. This `fastlane` action was not officially announced yet, but is already included in the last release. It will only set the correct UDID, as the code signing identity can just be set to default.

**Comment by phynet** [comment]
Excellent then! good job! I will keep my eye on it. 

Although,I will have to change mine later, because I'm using calabash-ios; it creates a new target, so the .pbxprj file changes his format, so I'll have to adjust it to the "new" format. It's already done but not pushed yet; but anyway, this is for a particular use only.

Thank you for sharing, your library looks good!
